[package]
name = "bottle"
version = "0.1.0"
authors = ["Yuta Taniguchi <yuta.taniguchi.y.t@gmail.com>"]

[dependencies]
mysql = "*"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
base64 = "0.9"
chrono = "0.4"
structopt = "0.2"
