[package]
name = "spring"
version = "0.1.0"
authors = ["Yuta Taniguchi <yuta.taniguchi.y.t@gmail.com>"]

[dependencies]
mysql = "*"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
base64 = "~0.6.0"
chrono = "0.4"
clap = "2.26"
